/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gaddie_mfidtime_Clock */

#ifndef _Included_net_gaddie_mfidtime_Clock
#define _Included_net_gaddie_mfidtime_Clock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gaddie_mfidtime_Clock
 * Method:    currentTimeNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_gaddie_mfidtime_Clock_currentTimeNanos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
